### ISSUE TITLE
scripts in /etc/local.d are not executed

### ISSUE THREAD

**Issue by FuyuriSeiichi** [sakaki-/gentoo-on-rpi-64bit#117]
Hi, 
I know this is not a serious issue. But I have some script that hardly fit anywhere else.
Does it require a dedicated service to run those script?

Thank you.

**Comment by jfikar** [comment]
You probably need `rc-update add local default`, see [the manual](https://wiki.gentoo.org/wiki//etc/local.d)

**Comment by FuyuriSeiichi** [comment]
OOPS, what a huge miss.
Thank you, jfikar.
I will just close this issue.
