### ISSUE TITLE
Unmasking vim

### ISSUE THREAD

**Issue by fredrik-eriksson** [sakaki-/gentoo-on-rpi-64bit#125]
I just wanted you to know I've successfully installed and used vim from the app-editors/vim-8.1.1846 ebuild, so you can probably remove the masks for vim and vim-core.

**Comment by sakaki-** [comment]
Thanks for the heads up! Confirmed that this now builds and runs OK, [masks removed](https://github.com/sakaki-/genpi64-overlay/commit/eb0c81f8fd5ad9f559b58198a1c1dbbd1c2b9c06).
Best, sakaki
