### ISSUE TITLE
Add "heif" USE flag

### ISSUE THREAD

**Issue by lzap** [sakaki-/gentoo-on-rpi-64bit#133]
Hello,

I would like to use RPi4 as nextCloud Photo manager however the very much needed HEIF USE flag is not set. Newer iPhones use HEIF/HEIC format instead of JPEG for capturing photos. Warning: There are some patents associated with this this could limit how binaries are distributed in countries with software patents.

**Comment by sakaki-** [comment]
Hi @lzap,

Maintaining the redistributable nature of the binary image is important for me. That said, setting `heif` globally doesn't appear to trigger any `bindist` USE or restrict properties, so maybe this has been reviewed by Gentoo devs already, or maybe the issue has just been overlooked.

If you could post an issue on the [Gentoo forums](https://forums.gentoo.org/index.php) about this, and get a confirmation that they regard it as OK from a licensing perspective to add (for a `bindist` system), I'll happily add it.

best, sakaki

**Comment by lzap** [comment]
Thanks.
