### ISSUE TITLE
Random mac-address on ethernet and wifi

### ISSUE THREAD

**Issue by Kosmoplayer** [sakaki-/gentoo-on-rpi-64bit#143]
I have home wifi with mac-address filter. Once my raspberry didn't connect to my wifi, and after some research I found what it just change macs on all interfaces. Probably after unsuccessful genup procedure. Why and where I can set it permanent?

**Comment by skulko** [comment]
most likely caused by Networkmanager:

https://blog.muench-johannes.de/networkmanager-disable-mac-randomization-314

**Comment by Kosmoplayer** [comment]
It's ridiculous this thing is on by default now.
