### ISSUE TITLE
sys-apps/rpi3-init-scripts shouldn't depend from >=x11-apps/xdm-1.1.11-r3 or should use USE="X"

### ISSUE THREAD

**Issue by RarogCmex** [sakaki-/gentoo-on-rpi-64bit#145]
Hi!
Thank you for your distribution, but I'm building raspberry pi 3 server so I doesn't need for any Xorg support (futhermore, it's weird)
sys-apps/rpi3-init-scripts depends from >=x11-apps/xdm-1.1.11-r3 that's pulled all Xorg packages.
I had to use my own ebuild without that dep.
So It should allow configured with USE="X"

**Comment by sakaki-** [comment]
Closed by https://github.com/sakaki-/genpi64-overlay/commit/3df619c9cf64d093be224afd4f34161e1dd0fd10

**Comment by RarogCmex** [comment]
Thank you Sakaki
