### ISSUE TITLE
Link Time Optimization

### ISSUE THREAD

**Issue by jonesmz** [sakaki-/gentoo-on-rpi-64bit#155]
Are you aware of the work being done here? 

https://github.com/InBetweenNames/gentooLTO

I've been using that configuration on my x86_64 machine for several weeks now, and am quite pleased with it.

It's not clear to me if AARCH64 would benefit in the same manner as x86_64, but I suspect that given the lower horse-power of the Raspberry Pi, the additional optimizations from LTO would have a bigger impact than on x86_64.

**Comment by sakaki-** [comment]
Yes, I use some packages borrowed from that overlay on the image, e.g. for python (https://github.com/sakaki-/genpi64-overlay/commit/4d0af9361ae121b41fba57f99ee2845d36d33aca) which has a 64-bit (vs 32-bit) performance penalty headwind to overcome (see e.g. [this post](https://www.raspberrypi.org/forums/viewtopic.php?p=1528347#p1528347)), where lto/pgo makes quite a difference.

I may expand the coverage going forward. Note that firefox does have lto available in the main tree build, and this is used on the current version (https://github.com/sakaki-/genpi64-overlay/commit/cb394d339b712f7c3cebe2ad6c803a7983967a8b).

**Comment by sakaki-** [comment]
Closing
