### ISSUE TITLE
Boot fails on Raspberry 400

### ISSUE THREAD

**Issue by pwasiewi** [sakaki-/gentoo-on-rpi-64bit#210]
Instant rebooting after staring a kernel and going to the sd system in Raspberry 400 for image 1.6.0 64bit.
Please, look at this raspberry and prepare the image for it or at least write a guide to generate an image for it.

**Comment by pwasiewi** [comment]
Now I have to do it myself :( EOL of this repo

**Comment by ALFonso6371** [comment]
I tried to replace the .elf, .dat and the .dtb file from the boot partition, with the latest version from raspberry Pi official. It can successfully boot, but has minor problem on shutting down.
